# Use Trusty as Emacs 26.x is failing on Xenial
# https://github.com/rejeep/evm/issues/125
dist: trusty

language: rust
rust:
  - stable

cache: cargo

sudo: false

before_install:
  - cargo install ripgrep || true
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - |
    case $EVM_EMACS in
    emacs-25.*) EMACS_GNUPGHOME=.cask/$(expr $EVM_EMACS : 'emacs-\(.*\)-travis')/elpa/gnupg ;;
    *) EMACS_GNUPGHOME=$HOME/.emacs.d/elpa/gnupg ;;
    esac
    mkdir -p "$EMACS_GNUPGHOME"
    chmod 700 "$EMACS_GNUPGHOME"
    wget 'https://git.savannah.gnu.org/cgit/emacs.git/plain/etc/package-keyring.gpg'
    gpg --homedir "$EMACS_GNUPGHOME" --import package-keyring.gpg
  - cask --verbose
env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-26.2-travis
  # - EVM_EMACS=emacs-git-snapshot-travis
script:
  - emacs --version
  - cask exec ert-runner

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis
